services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe-cuda
    environment:
      DISPLAY: ${DISPLAY:?err}
      NVIDIA_DRIVER_CAPABILITIES: all
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: ${DIR_MAPS:?err}
        target: ${DIR_MAPS_TARGET:?err}
        read_only: true
      - type: bind
        source: ${DIR_AUTOWARE_DATA:?err}
        target: ${DIR_AUTOWARE_DATA_TARGET:?err}
        read_only: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
