services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe-cuda
    env_file:
      - .env
    environment:
      DISPLAY: ${DISPLAY:?err}
      NVIDIA_DRIVER_CAPABILITIES: all
    privileged: true
    network_mode: host
    volumes:
      - ${DIR_MAPS:?err}:${DIR_MAPS_TARGET:?err}:ro
      - ${DIR_AUTOWARE_DATA:?err}:${DIR_AUTOWARE_DATA:?err}:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
